### PR TITLE
Layout adjustments (scenario list and cohort list)

### PR DESCRIPTION
**Pull request by enatario**
This PR makes some visual changes to sync the cohort list page with the scenario list page (within the grid format)

Also ran an npm audit fix which created a small package update.

### CODE REVIEW

**Comment by enatario** [comment]
@jesdaigle looks like slack's still down (ugh). if you have a chance today, would love a review on this! :)

**Review by evmiguel — COMMENTED** [review]
@enatario There are some build issues that I'm looking into before merging

**Review by evmiguel — APPROVED** [review]
Approving. The commits associated with the PR changes are strange, and I will take the branch passing as a good sign.

**Comment by enatario** [comment]
Hooray! Thanks @evmiguel!

**Pull request merged**
